# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pczebra's Blogs # ex. I m Chuan
name: pczebra # ex. DONGChuan
email: 1240693298@qq.com
location: Hangzhou, China # ex. Nice, France
company: H3C
company_url: https://www.h3c.com/cn
github_url: https://github.com/pczebra
github_username: pczebra
description: pczebra的个人博客网站
favicon: favicon.jpg # Image must be in assets/images
repository: pczebra/pczebra.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://pczebra.github.io/pczebra
baseurl: /pczebra

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

source: .
destination: ./_site

quiet: false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Giscus
giscus:
  enable: true
  repo: pczebra/pczebra
  id: R_kgDOI5MmWA
  category: Announcements
  cateId: DIC_kwDOI5MmWM4CT-QH
  mapping: pathname

# Pagination
paginate: 10
paginate_path: "page:num"

# Navigation. If you do not like these modules, just remove them :D
navs:
  - href: /
    label: 首页

  - href: /blog
    label: 博客

  - href: /about
    label: 关于我

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics:
  provider: google
  google:
    tracking_id: "tracking_id" # ex. UA-72165600-X

# For about.html. Fell free to create your own!
skill_software_keywords:
  [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords:
  [
    HTML,
    CSS,
    JS,
    JQuery,
    Ajax,
    AngularJS,
    NodeJS,
    ExpressJS,
    MongoDB,
    Redis,
    PHP,
    Symfony,
    Boostrap,
  ]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
